import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "lib/utils": "src/lib/utils.ts",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/button": "src/components/button.tsx",
    "components/card": "src/components/card.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/command": "src/components/command.tsx",
    "components/copy-button": "src/components/copy-button.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/input": "src/components/input.tsx",
    "components/label": "src/components/label.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/theme-toggle": "src/components/theme-toggle.tsx",
    "components/toast": "src/components/toast.tsx",
    "components/toaster": "src/components/toaster.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/use-toast": "src/components/use-toast.ts",
  },
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  banner: {
    js: '"use client";',
  },
  external: [
    "react",
    "react-dom",
    "next-themes",
    "@radix-ui/react-alert-dialog",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-dialog",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-icons",
    "@radix-ui/react-label",
    "@radix-ui/react-popover",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-slot",
    "@radix-ui/react-switch",
    "@radix-ui/react-tabs",
    "@radix-ui/react-toast",
    "@radix-ui/react-tooltip",
    "class-variance-authority",
    "clsx",
    "cmdk",
    "lucide-react",
    "react-resizable-panels",
    "sonner",
    "tailwind-merge",
  ],
});
